//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
        {
            switch (source, typeof(TDestination))
            {
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel());
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel());
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch());
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.NewDocumentInput s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand());
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch());
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel d):
                    return (dynamic)MapInternal(s, d);
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel d):
                    return (dynamic)MapInternal(s, d);
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch d):
                    return (dynamic)MapInternal(s, d);
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.NewDocumentInput s, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand d):
                    return (dynamic)MapInternal(s, d);
                case (AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData s, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch d):
                    return (dynamic)MapInternal(s, d);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to existing {typeof(TDestination).Name} has not been configured.");
            }
        }

        private AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel MapInternal(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData source, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel destination)
        {
            destination.Id = source.Id;
            destination.DocTitle = source.DocTitle;
            destination.Creator = source.CreateUser == null ? source.DocUser : source.CreateUser.UserName;
            destination.CreateDate = source.CreateDate;
            destination.ChangeDate = source.ChangeDate;
            destination.DocDeleteDate = source.DeleteDate;
            destination.DocDate = source.DocDate;
            destination.Length = source.DocLen;
            destination.Type = source.Type == null ? null : source.Type.Code;
            destination.SortIndex = source.Type == null ? null : source.Type.SortIndex;

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel MapInternal(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData source, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel destination)
        {
            destination.FileName = source.Type == null ? (source.DocTitle ?? string.Empty) : $"{source.DocTitle}.{source.Type.Code.ToLower()}";
            destination.FileFormat = source.Type == null ? string.Empty : source.Type.Code;
            destination.Content = source.DocContent.DocBinary;

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch MapInternal(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData source, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch destination)
        {
            destination.NewDocTitle = source.DocTitle;
            destination.NewTypeCode = source.Type?.Code;

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand MapInternal(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.NewDocumentInput source, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand destination)
        {
            destination.DocDate = source.DocDate;
            destination.DocType = source.DocType;
            destination.Keywords = source.Keywords;
            destination.Format = source.Format;
            destination.FileName = source.File?.Name;

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch MapInternal(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData source, AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch destination)
        {
            destination.DocTitle = source.DocTitle;
            destination.DocDate = source.DocDate;

            return destination;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
        {
            switch (source)
            {
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData> s:
                    return ProjectInternal<TDestination>(s);
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.NewDocumentInput> s:
                    return ProjectInternal<TDestination>(s);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocMetaData> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocSearchViewModel()
                        {
                            Id = source.Id,
                            DocTitle = source.DocTitle,
                            Creator = source.CreateUser == null ? source.DocUser : source.CreateUser.UserName,
                            CreateDate = source.CreateDate,
                            ChangeDate = source.ChangeDate,
                            DocDeleteDate = source.DeleteDate,
                            DocDate = source.DocDate,
                            Length = source.DocLen,
                            Type = source.Type == null ? null : source.Type.Code,
                            SortIndex = source.Type == null ? null : source.Type.SortIndex
                        }));
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.DocumentDownloadViewModel()
                        {
                            FileName = source.Type == null ? (source.DocTitle ?? string.Empty) : $"{source.DocTitle}.{source.Type.Code.ToLower()}",
                            FileFormat = source.Type == null ? string.Empty : source.Type.Code,
                            Content = source.DocContent.DocBinary
                        }));
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.MoveDocPatch()
                        {
                            NewDocTitle = source.DocTitle,
                            NewTypeCode = source.Type != null ? source.Type.Code : null
                        }));
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.ModifyDocPatch()
                        {
                            DocTitle = source.DocTitle,
                            DocDate = source.DocDate
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.NewDocumentInput> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Troubleshoot.Sources.CreateDocumentCommand()
                        {
                            DocDate = source.DocDate,
                            DocType = source.DocType,
                            Keywords = source.Keywords,
                            Format = source.Format,
                            FileName = source.File != null ? source.File.Name : null
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }
    }
}
