//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
        {
            switch (source, typeof(TDestination))
            {
                case (AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedSource s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination());
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedSource s, AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination d):
                    return (dynamic)MapInternal(s, d);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to existing {typeof(TDestination).Name} has not been configured.");
            }
        }

        private AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination MapInternal(AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedSource source, AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination destination)
        {
            destination.Id = source.Id;
            destination.CreateUserID = source.CreateUserID;
            destination.CreateDate = source.CreateDate;

            return destination;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
        {
            switch (source)
            {
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedSource> s:
                    return ProjectInternal<TDestination>(s);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedSource> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.Inheritance.Sources.DerivedDestination()
                        {
                            Id = source.Id,
                            CreateUserID = source.CreateUserID,
                            CreateDate = source.CreateDate
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }
    }
}
