//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
        {
            switch (source, typeof(TDestination))
            {
                case (AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj());
                // TODO: Need the other switch cases from most specific to least
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj[]):
                    return (dynamic)global::System.Linq.Enumerable.ToArray(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, System.Type t) when typeof(global::System.Collections.Generic.ISet<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>).IsAssignableFrom(t):
                    return (dynamic)global::System.Linq.Enumerable.ToHashSet(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, System.Type t) when typeof(global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>).IsAssignableFrom(t):
                    return (dynamic)global::System.Linq.Enumerable.ToList(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj s, AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj d):
                    return (dynamic)MapInternal(s, d);
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj[]):
                    return (dynamic)global::System.Linq.Enumerable.ToArray(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, global::System.Collections.Generic.ISet<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>):
                    return (dynamic)global::System.Linq.Enumerable.ToHashSet(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                case (global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s, global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>):
                    return (dynamic)global::System.Linq.Enumerable.ToList(EnumerableInternal<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj>(s));
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to existing {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Collections.Generic.IEnumerable<TDestination> EnumerableInternal<TDestination>(global::System.Collections.Generic.IEnumerable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> sourceEnumerable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj):
                    return global::System.Linq.Enumerable.Cast<TDestination>(
                        global::System.Linq.Enumerable.Select(sourceEnumerable, source => new AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj()
                        {
                            Id = source.Id,
                            Type = source.Type,
                            Timestamp = source.Timestamp,
                            InUse = source.InUse
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceEnumerable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj MapInternal(AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj source, AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj destination)
        {
            destination.Id = source.Id;
            destination.Type = source.Type;
            destination.Timestamp = source.Timestamp;
            destination.InUse = source.InUse;

            return destination;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
        {
            switch (source)
            {
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> s:
                    return ProjectInternal<TDestination>(s);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullSourceObj> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.CollectionMapping.Sources.FullDestinationObj()
                        {
                            Id = source.Id,
                            Type = source.Type,
                            Timestamp = source.Timestamp,
                            InUse = source.InUse
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }
    }
}
