//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
            where TDestination : new() => Map<TDestination>(source, new TDestination());
        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (SampleMappingConsumer.Models.SourceObj s, SampleMappingConsumer.Models.Destination1Obj d):
                    d.Id = s.Id;
                    d.Type = s.Type;
                    break;
                case (SampleMappingConsumer.Models.SourceObj s, SampleMappingConsumer.Models.Destination2Obj d):
                    d.Id = s.Id;
                    d.Type = s.Type;
                    break;
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }

            return destination;
        }
    }
}
