//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
            where TDestination : new() => Map<TDestination>(source, new TDestination());
        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceObj s, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested d):
                    MapInternal(s, d);
                    break;
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }

            return destination;
        }

        private void MapInternal(AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceObj source, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested destination)
        {
            destination.ChildObjValue = source.ChildObj == null || source.ChildObj.Value == null ? "something else" : source.ChildObj.Value;
            destination.NonNullString = source.ChildObj == null || source.ChildObj.Value == null ? "my default" : source.ChildObj.Value;
            destination.ChildObjOtherValue = source.ChildObj == null || source.ChildObj.OtherValue == null ? source.OtherNullableString : source.ChildObj.OtherValue;
            destination.NullableString = source.ChildObj == null || source.ChildObj.OtherValue == null ? (source.ChildObj == null ? null : source.ChildObj.Value) : source.ChildObj.OtherValue;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
            where TDestination : new()
        {
            var destInstance = new TDestination();
            switch (source, destInstance)
            {
                case (global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceObj> s, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested d):
                    return global::System.Linq.Queryable.Cast<TDestination>(ProjectInternal(s, d));
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested> ProjectInternal(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceObj> sourceQueryable, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested _)
        {
            return global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationObjFromNested()
            {
                ChildObjValue = source.ChildObj == null || source.ChildObj.Value == null ? "something else" : source.ChildObj.Value,
                NonNullString = source.ChildObj == null || source.ChildObj.Value == null ? "my default" : source.ChildObj.Value,
                ChildObjOtherValue = source.ChildObj == null || source.ChildObj.OtherValue == null ? source.OtherNullableString : source.ChildObj.OtherValue,
                NullableString = source.ChildObj == null || source.ChildObj.OtherValue == null ? (source.ChildObj == null ? null : source.ChildObj.Value) : source.ChildObj.OtherValue
            });
        }
    }
}
