//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
            where TDestination : new() => Map<TDestination>(source, new TDestination());
        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceWithNullableValueTypes s, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationForNullableValueTypes d):
                    d.NonNullableRefSimpleMap = s.NonNullableRefType;
                    d.NonNullableRefMapWithStaticFallback = s.NullableRefType ?? "test";
                    d.NonNullableRefMapWithPropertyFallback = s.NullableRefType ?? s.NonNullableRefType;
                    d.NullableRefSimpleMap = s.NullableRefType;
                    d.NullableRefMapWithStaticFallback = s.NullableRefType ?? "test";
                    d.NullableRefMapWithPropertyFallback = s.NullableRefType ?? s.NonNullableRefType;
                    d.NullableRefType = s.NullableRefType ?? "test";
                    d.SourceWithNullableValueTypesNullableRefType = s.NullableRefType ?? s.NonNullableRefType;
                    d.NonNullableValueSimpleMap = s.NonNullableValueType;
                    d.NonNullableValueMapWithStaticFallback = s.NullableValueType ?? 99;
                    d.NonNullableValueMapWithPropertyFallback = s.NullableValueType ?? s.NonNullableValueType;
                    d.NullableValueSimpleMap = s.NullableValueType;
                    d.NullableValueMapWithStaticFallback = s.NullableValueType ?? 99;
                    d.NullableValueMapWithPropertyFallback = s.NullableValueType ?? s.NonNullableValueType;
                    d.NullableValueType = s.NullableValueType ?? 99;
                    d.SourceWithNullableValueTypesNullableValueType = s.NullableValueType ?? s.NonNullableValueType;
                    break;
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }

            return destination;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
            where TDestination : new()
        {
            var destInstance = new TDestination();
            switch (source, destInstance)
            {
                case (global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.SourceWithNullableValueTypes> s, AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationForNullableValueTypes):
                    return global::System.Linq.Queryable.Cast<TDestination>(global::System.Linq.Queryable.Select(s, src => new AutomapGenerator.Generator.VerificationTests.NullFallbacks.Sources.DestinationForNullableValueTypes()
                    {
                        NonNullableRefSimpleMap = src.NonNullableRefType,
                        NonNullableRefMapWithStaticFallback = src.NullableRefType != null ? src.NullableRefType : "test",
                        NonNullableRefMapWithPropertyFallback = src.NullableRefType != null ? src.NullableRefType : src.NonNullableRefType,
                        NullableRefSimpleMap = src.NullableRefType,
                        NullableRefMapWithStaticFallback = src.NullableRefType != null ? src.NullableRefType : "test",
                        NullableRefMapWithPropertyFallback = src.NullableRefType != null ? src.NullableRefType : src.NonNullableRefType,
                        NullableRefType = src.NullableRefType != null ? src.NullableRefType : "test",
                        SourceWithNullableValueTypesNullableRefType = src.NullableRefType != null ? src.NullableRefType : src.NonNullableRefType,
                        NonNullableValueSimpleMap = src.NonNullableValueType,
                        NonNullableValueMapWithStaticFallback = src.NullableValueType != null ? src.NullableValueType : 99,
                        NonNullableValueMapWithPropertyFallback = src.NullableValueType != null ? src.NullableValueType : src.NonNullableValueType,
                        NullableValueSimpleMap = src.NullableValueType,
                        NullableValueMapWithStaticFallback = src.NullableValueType != null ? src.NullableValueType : 99,
                        NullableValueMapWithPropertyFallback = src.NullableValueType != null ? src.NullableValueType : src.NonNullableValueType,
                        NullableValueType = src.NullableValueType != null ? src.NullableValueType : 99,
                        SourceWithNullableValueTypesNullableValueType = src.NullableValueType != null ? src.NullableValueType : src.NonNullableValueType
                    }));
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }
        }
    }
}
