//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
            where TDestination : new() => Map<TDestination>(source, new TDestination());
        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SourceObjWithNesting s, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc d):
                    MapInternal(s, d);
                    break;
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }

            return destination;
        }

        private void MapInternal(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SourceObjWithNesting source, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc destination)
        {
            destination.Id = source.Id;
            destination.ChildObjDescription = source.ChildObj?.Description;
            destination.ChildObjOtherProp = source.ChildObj?.OtherProp;
            destination.SourceObjWithNestingChildObjDescription = source.ChildObj?.Description;
            destination.ChildObjNestedSourceOtherProp = source.ChildObj?.OtherProp;
            destination.NestedSourceDescription = source.NestedSource?.Description;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
            where TDestination : new()
        {
            var destInstance = new TDestination();
            switch (source, destInstance)
            {
                case (global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SourceObjWithNesting> s, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc d):
                    return global::System.Linq.Queryable.Cast<TDestination>(ProjectInternal(s, d));
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc> ProjectInternal(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SourceObjWithNesting> sourceQueryable, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc _)
        {
            return global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.DestinationFromNestedSrc()
            {
                Id = source.Id,
                ChildObjDescription = source.ChildObj != null ? source.ChildObj.Description : null,
                ChildObjOtherProp = source.ChildObj != null ? source.ChildObj.OtherProp : null,
                SourceObjWithNestingChildObjDescription = source.ChildObj != null ? source.ChildObj.Description : null,
                ChildObjNestedSourceOtherProp = source.ChildObj != null ? source.ChildObj.OtherProp : null,
                NestedSourceDescription = source.NestedSource != null ? source.NestedSource.Description : null
            });
        }
    }
}
