//HintName: Mapper.g.cs
// <auto-generated/>
namespace AutomapGenerator
{
    [global::System.CodeDom.Compiler.GeneratedCode("AutomapGenerator.SourceGenerator.MapperGenerator", "1.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public class Mapper : IMapper
    {
        public TDestination Map<TDestination>(object source)
        {
            switch (source, typeof(TDestination))
            {
                case (AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleSourceObj s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj());
                case (AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.OtherSimpleSourceObj s, System.Type t) when t == typeof(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj):
                    return (dynamic)MapInternal(s, new AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj());
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        public TDestination Map<TDestination>(object source, TDestination destination)
        {
            switch (source, destination)
            {
                case (AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleSourceObj s, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj d):
                    MapInternal(s, d);
                    break;
                case (AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.OtherSimpleSourceObj s, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj d):
                    MapInternal(s, d);
                    break;
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to existing {typeof(TDestination).Name} has not been configured.");
            }

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj MapInternal(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleSourceObj source, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj destination)
        {
            destination.Id = source.Id;
            destination.Type = source.Type;

            return destination;
        }

        private AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj MapInternal(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.OtherSimpleSourceObj source, AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj destination)
        {
            destination.Id = source.Id;
            destination.Type = source.Type;

            return destination;
        }

        public global::System.Linq.IQueryable<TDestination> ProjectTo<TDestination>(global::System.Linq.IQueryable<object> source)
        {
            switch (source)
            {
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleSourceObj> s:
                    return ProjectInternal<TDestination>(s);
                case global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.OtherSimpleSourceObj> s:
                    return ProjectInternal<TDestination>(s);
                default:
                    throw new MappingException($"Mapping from {source.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleSourceObj> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj()
                        {
                            Id = source.Id,
                            Type = source.Type
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }

        private global::System.Linq.IQueryable<TDestination> ProjectInternal<TDestination>(global::System.Linq.IQueryable<AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.OtherSimpleSourceObj> sourceQueryable)
        {
            switch (typeof(TDestination))
            {
                case System.Type t when t == typeof(AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj):
                    return global::System.Linq.Queryable.Cast<TDestination>(
                        global::System.Linq.Queryable.Select(sourceQueryable, source => new AutomapGenerator.Generator.VerificationTests.CreateMap.Sources.SimpleDestinationObj()
                        {
                            Id = source.Id,
                            Type = source.Type
                        }));
                default:
                    throw new MappingException($"Mapping from {sourceQueryable.GetType().Name} to new {typeof(TDestination).Name} has not been configured.");
            }
        }
    }
}
